# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MotionComponentsExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MotionComponents', :path => '../'
  pod 'MotionComponents/Tools', :path => '../'
end
